# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kxjsq_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(430, 610)
        MainWindow.setMinimumSize(QtCore.QSize(430, 610))
        MainWindow.setMaximumSize(QtCore.QSize(430, 610))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("kxjsq.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(100, 450, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 450, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 450, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 380, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 380, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 380, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(260, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(180, 520, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_dian = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dian.setGeometry(QtCore.QRect(100, 520, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_dian.setFont(font)
        self.pushButton_dian.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_dian.setObjectName("pushButton_dian")
        self.pushButton_dengyu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dengyu.setGeometry(QtCore.QRect(260, 520, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_dengyu.setFont(font)
        self.pushButton_dengyu.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_dengyu.setObjectName("pushButton_dengyu")
        self.pushButton_chu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chu.setGeometry(QtCore.QRect(340, 520, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_chu.setFont(font)
        self.pushButton_chu.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_chu.setObjectName("pushButton_chu")
        self.pushButton_cheng = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cheng.setGeometry(QtCore.QRect(340, 450, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cheng.setFont(font)
        self.pushButton_cheng.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_cheng.setObjectName("pushButton_cheng")
        self.pushButton_jian = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jian.setGeometry(QtCore.QRect(340, 380, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_jian.setFont(font)
        self.pushButton_jian.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_jian.setObjectName("pushButton_jian")
        self.pushButton_jia = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jia.setGeometry(QtCore.QRect(340, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_jia.setFont(font)
        self.pushButton_jia.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_jia.setObjectName("pushButton_jia")
        self.pushButton_sin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sin.setGeometry(QtCore.QRect(180, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_sin.setFont(font)
        self.pushButton_sin.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_sin.setObjectName("pushButton_sin")
        self.pushButton_tan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tan.setGeometry(QtCore.QRect(340, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_tan.setFont(font)
        self.pushButton_tan.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_tan.setObjectName("pushButton_tan")
        self.pushButton_tab = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tab.setGeometry(QtCore.QRect(340, 240, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_tab.setFont(font)
        self.pushButton_tab.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_tab.setObjectName("pushButton_tab")
        self.pushButton_cos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cos.setGeometry(QtCore.QRect(260, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cos.setFont(font)
        self.pushButton_cos.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_cos.setObjectName("pushButton_cos")
        self.pushButton_kf = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kf.setGeometry(QtCore.QRect(20, 310, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_kf.setFont(font)
        self.pushButton_kf.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_kf.setObjectName("pushButton_kf")
        self.pushButton_pai = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pai.setGeometry(QtCore.QRect(20, 380, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_pai.setFont(font)
        self.pushButton_pai.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_pai.setObjectName("pushButton_pai")
        self.pushButton_jiecheng = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jiecheng.setGeometry(QtCore.QRect(20, 520, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_jiecheng.setFont(font)
        self.pushButton_jiecheng.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_jiecheng.setObjectName("pushButton_jiecheng")
        self.pushButton_x_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_x_2.setGeometry(QtCore.QRect(20, 240, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_x_2.setFont(font)
        self.pushButton_x_2.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_x_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("x2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_x_2.setIcon(icon1)
        self.pushButton_x_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_x_2.setObjectName("pushButton_x_2")
        self.pushButton_e = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_e.setGeometry(QtCore.QRect(20, 450, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_e.setFont(font)
        self.pushButton_e.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_e.setObjectName("pushButton_e")
        self.pushButton_tw = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tw.setGeometry(QtCore.QRect(260, 240, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_tw.setFont(font)
        self.pushButton_tw.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_tw.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("sc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_tw.setIcon(icon2)
        self.pushButton_tw.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_tw.setObjectName("pushButton_tw")
        self.pushButton_c = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_c.setGeometry(QtCore.QRect(100, 240, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_c.setFont(font)
        self.pushButton_c.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_c.setObjectName("pushButton_c")
        self.pushButton_ce = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ce.setGeometry(QtCore.QRect(180, 240, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_ce.setFont(font)
        self.pushButton_ce.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_ce.setObjectName("pushButton_ce")
        self.pushButton_x_y = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_x_y.setGeometry(QtCore.QRect(20, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_x_y.setFont(font)
        self.pushButton_x_y.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_x_y.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("xy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_x_y.setIcon(icon3)
        self.pushButton_x_y.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_x_y.setObjectName("pushButton_x_y")
        self.pushButton_log = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_log.setGeometry(QtCore.QRect(100, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_log.setFont(font)
        self.pushButton_log.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_log.setObjectName("pushButton_log")
        self.label_now = QtWidgets.QLabel(self.centralwidget)
        self.label_now.setGeometry(QtCore.QRect(20, 80, 390, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_now.setFont(font)
        self.label_now.setStyleSheet("")
        self.label_now.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_now.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_now.setText("")
        self.label_now.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_now.setObjectName("label_now")
        self.label_his = QtWidgets.QLabel(self.centralwidget)
        self.label_his.setGeometry(QtCore.QRect(110, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_his.setFont(font)
        self.label_his.setStyleSheet("background:rgb(230, 230, 230)")
        self.label_his.setText("")
        self.label_his.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_his.setObjectName("label_his")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(20, 10, 62, 62))
        self.label_logo.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_logo.setText("")
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.pushButton_arccos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arccos.setGeometry(QtCore.QRect(260, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_arccos.setFont(font)
        self.pushButton_arccos.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_arccos.setObjectName("pushButton_arccos")
        self.pushButton_arctan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arctan.setGeometry(QtCore.QRect(340, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_arctan.setFont(font)
        self.pushButton_arctan.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_arctan.setObjectName("pushButton_arctan")
        self.pushButton_arcsin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_arcsin.setGeometry(QtCore.QRect(180, 170, 71, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_arcsin.setFont(font)
        self.pushButton_arcsin.setStyleSheet("background: rgb(230, 230, 230)")
        self.pushButton_arcsin.setObjectName("pushButton_arcsin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "科学计算器"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_dian.setText(_translate("MainWindow", "."))
        self.pushButton_dengyu.setText(_translate("MainWindow", "="))
        self.pushButton_chu.setText(_translate("MainWindow", "÷"))
        self.pushButton_cheng.setText(_translate("MainWindow", "×"))
        self.pushButton_jian.setText(_translate("MainWindow", "-"))
        self.pushButton_jia.setText(_translate("MainWindow", "+"))
        self.pushButton_sin.setText(_translate("MainWindow", "sin"))
        self.pushButton_tan.setText(_translate("MainWindow", "tan"))
        self.pushButton_tab.setText(_translate("MainWindow", "↑"))
        self.pushButton_cos.setText(_translate("MainWindow", "cos"))
        self.pushButton_kf.setText(_translate("MainWindow", "√"))
        self.pushButton_pai.setText(_translate("MainWindow", "π"))
        self.pushButton_jiecheng.setText(_translate("MainWindow", "n!"))
        self.pushButton_e.setText(_translate("MainWindow", "e"))
        self.pushButton_c.setText(_translate("MainWindow", "C"))
        self.pushButton_ce.setText(_translate("MainWindow", "CE"))
        self.pushButton_log.setText(_translate("MainWindow", "log"))
        self.pushButton_arccos.setText(_translate("MainWindow", "arccos"))
        self.pushButton_arctan.setText(_translate("MainWindow", "arctan"))
        self.pushButton_arcsin.setText(_translate("MainWindow", "arcsin"))

